config/routes.rb
Rails.application.routes.draw do

    root to: 'homes#top'
    get 'home/about' => 'homes#about'

    get 'bookmarks/create'
    get 'bookmarks/destroy'

    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :users

    resources :articles do
        resource  :favorites, only: [:create, :destroy]
        resources :post_comments, only: [:create, :edit, :update, :destroy]
        resource  :bookmarks, only: [:create, :destroy]

        # ブックマークの一覧表示に使用するルーティング
        get			:bookmarks, on: :collection

    end

    resources :questions do
        resources :answers, only: [:create, :edit, :update, :destroy]
        resource  :sympathizes, only: [:create, :destroy]
    end

end

app/models/answer.rb
class Answer < ApplicationRecord

	belongs_to :user
	belongs_to :question

	validates :content, presence: true

	attachment :answer_image


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	has_many :bookmarks, dependent: :destroy

	# current_userが、対象の投稿に "いいね" または "ブックマーク" をしているか判定するメソッド

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
    end

  	def bookmark_by?(user)
    	bookmarks.where(user_id: user.id).exists?
  	end

  	# ここまで

	validates :town, presence: true, length: { maximum: 40 }
	validates :family_makeup, presence: true, length: { maximum: 40 }
	validates :maker, presence: true, length: { maximum: 40 }
	validates :sales_form, presence: true, length: { maximum: 40 }
	validates :modality, presence: true, length: { maximum: 40 }
	validates :style, presence: true, length: { maximum: 40 }
	validates :purchase_price, presence: true, length: { maximum: 40 }
	validates :content, presence: true

	attachment :article_image


end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :user
  belongs_to :article

  # 1人のユーザーが同じ投稿を複数回bookmarkできないようにする
  validates :user_id, uniqueness: { scope: :article_id }


end

app/models/category.rb
class Category < ApplicationRecord

	has_many :questions

end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :article

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :user
	belongs_to :article

	validates :comment, presence: true

	attachment :post_comment_image


end

app/models/question.rb
class Question < ApplicationRecord

	has_many :answers, dependent: :destroy
	has_many :sympathizes, dependent: :destroy

	belongs_to :user
	belongs_to :category

	validates :title, presence: true, length: { maximum: 40 }

	attachment :question_image

	def sympathized_by?(user)
		sympathizes.where(user_id: user.id).exists?
	end

end

app/models/sympathize.rb
class Sympathize < ApplicationRecord

	belongs_to :user
	belongs_to :question

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :sympathizes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # ブックマーク機能のアソシエーション
  has_many :bookmarks, dependent: :destroy

  # ユーザーがブックマークした投稿を直接アソシエーションで取得できるように"bookmark_articles"を定義
  has_many :bookmark_articles, through: :bookmarks, source: :article

  validates :name, presence: true, length: { maximum: 10 }

  attachment :profile_image

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def top
    end

    def about
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

    before_action :authenticate_user!

    def index
        # ランキング機能
        @ranks = Question.find(Sympathize.group(:question_id).order('count(question_id) desc').limit(3).pluck(:question_id))
        # 一覧表示機能
        @active_questions = Question.where(status: true).page(params[:page]).reverse_order.per(5)
        @passive_questions = Question.where(status: false).page(params[:page]).reverse_order.per(5)
        # カテゴリー検索機能
        @categories = Category.all

        if params[:category_id].present?
        # params[:category_id]が存在する場合、カテゴリーに紐づく質問のみを取得する
        @category = Category.find(params[:category_id].to_i)
        @questions = Question.where(category_id: @category.id)
        else
        # params[:category_id]が存在しない場合、質問を全て取得する
        @questions = Question.all
        end
    end

    def show
        @question = Question.find(params[:id])
        # 回答を投稿するためのインスタンス変数
        @answer = Answer.new
    end

    def new
        @question = Question.new
        @user = current_user
    end

    def create
        @question = Question.new(question_params)
        @question.user_id = current_user.id

        if  @question.save
            flash[:notice] = "質問を投稿しました。"
            redirect_to question_path(@question)
        else
            flash[:notice] = "入力されていない項目があるか、字数制限を超過しています。"
            @question = Question.new
            @user = current_user
            render(:new)
        end
    end

    def edit
        @question = Question.find(params[:id])

        if  @question.user_id != current_user.id
            flash[:notice] = "権限がありません。"
            redirect_to question_path(@question)
        end
    end

    def update
        @question = Question.find(params[:id])

        if @question.update(question_params)
           flash[:notice] = "質問を編集しました。"
           redirect_to question_path(@question)
        else
            flash[:notice] = "未入力の項目があります。"
            render(:edit)
        end
    end

    def destroy
        @question = Question.find(params[:id])
        @question.destroy
        redirect_to questions_path
    end

end

private

    def question_params
        params.require(:question).permit(:category_id, :status, :title, :content, :best_answer_id)
    end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sympathizes_helper.rb
module SympathizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/questions/_answer.html.erb
<div class="panel panel-default">
    <div class="panel-heading text-center">
        <div class="panel-title">回答</div>
    </div>
    <div class="panel-body">
        <% if question.answers.blank? %>
            <div class="blank text-center">まだ回答がありません。</div>
        <% end %>

        <!-- アンサー一覧表示 -->
        <% question.answers.each do |answer| %>

        <div class="panel">
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-3">
                        <%= link_to user_path(answer.user) do %>
                            <%= attachment_image_tag answer.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size: '50x50', class: "img-responsive center-block" %><br>
                            <div class="text-center"><%= answer.user.name %></div>
                        <% end %>
                    </div>
                    <div class="col-xs-9">
                        <%= simple_format(answer.content, size: "400x100") %>
                    </div>
                </div>

                <div class="answer_action text-right">

                        <!-- ベストアンサーボタン -->

                        <% if @question.user == current_user %>
                            <!-- 投稿されている全ての回答に対して「この回答をベストアンサーにする！」を表示させる -->
                            <% if @question.best_answer_id == nil %>

                                <%= button_to "この回答をベストアンサーにする！",
                                    {controller: 'questions', action: 'update'},
                                    {method: :put, params: {question:
                                    {id: @question.id,
                                    title: @question.title,
                                    content: @question.content,
                                    status: @question.status,
                                    category_id: @question.category_id,
                                    user_id: @question.user_id,
                                    best_answer_id: answer.id}},
                                    class: "bestanswer"} %>

                            <% end %>
                        <% end %>

                        <!-- ベストアンサーの解除ボタン（質問投稿者に対してのみ表示） -->
                        <% if @question.best_answer_id == answer.id %>
                            <% if @question.user == current_user %>

                                <%= button_to "このベストアンサーを解除する",
                                    {controller: 'questions', action: 'update'},
                                    {method: :put, params: {question:
                                    {title: @question.title,
                                    content: @question.content,
                                    status: @question.status,
                                    category_id: @question.category_id,
                                    user_id: @question.user_id,
                                    best_answer_id: nil}},
                                    class: "bestanswer"} %>

                            <% else %>

                                <!-- 質問投稿者以外には「この回答がベストアンサーに選ばれました！」を表示する -->
                                <span class="reactionall">
                                    <i class= "glyphicon glyphicon-star"></i>
                                    <span>この回答がベストアンサーに選ばれました！</span>
                                </span>

                            <% end %>
                        <% end %>

                        <!-- 各リンク -->
                        <% if answer.user == current_user %>
                            <%= link_to "編集", edit_question_answer_path(question,answer),　local: true %>
                        <% end %>

                        <% if answer.user == current_user %>
                            <!-- ベストアンサーに選ばれた回答は削除ボタンを表示させない -->
                            <% if @question.best_answer_id != answer.id %>
                                <%= link_to "削除", question_answer_path(question,answer), method: :delete , local: true, "data-confirm" => "Are you sure?" %>
                            <% end %>
                        <% end %>

                        <!-- 日付 -->
                        <%= answer.created_at.strftime('%Y/%m/%d') %>

                    </div>
                </div>
            </div>
        <% end %>

        <!-- アンサー一覧表示ここまで -->

    </div>
</div>

app/views/questions/_answer_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading text-center">
        <div class="panel-title">回答を投稿する</div>
    </div>
    <div class="panel-body">

        <!-- 質問ステータスが「回答受付中」であれば回答フォームを表示させる -->
        <% if @question.status == true %>

            <%= form_with(model:[question, answer], url: question_answers_path(question.id), method: :POST, local: true) do |f| %>

                <table class="table table-hover table-inverse">
                    <tbody>
                        <tr>
                            <td><%= f.text_area(:content)%></td>
                        </tr>
                    </tbody>
                </table>

                <%= f.submit("回答を投稿する", class: "btn btn-default") %>

            <% end %>

        <% else %>

            <!-- 質問ステータスが「回答済み」であれば回答フォームを表示させない -->
            <div class="text-center">
                <span style="color: red;">この質問についての回答は締め切りました。</span>
            </div>

        <% end %>
    </div>
</div>

app/views/questions/_index.html.erb
<div class="panel panel-default">
    <div class="panel-heading text-center">回答受付中の質問一覧</div>
    <div class="panel-body">

        <!-- 回答受付中の質問一覧 -->
        <% active_questions.each do |active| %>

            <span class="row">
                <span class="col-xs-1"></span>
                <span class="col-xs-7">
                    <%= link_to active.title, question_path(active) %>
                </span>
                <span class="col-xs-3  text-right">
                    <% if active.status == true %>
                        <div class="statusbutton"> 回答受付中 </div>
                    <% end %>
                </span>
                <span class="col-xs-1"></span>
            </span>

        <% end %>

        <!-- ページネーション -->
        <div class="row">
            <div class="col-xs-1"></div>
            <div class="col-xs-10"><%= paginate active_questions %></div>
            <div class="col-xs-1"></div>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading text-center">&nbsp;&nbsp;解決済みの質問一覧&nbsp;&nbsp;</div>
    <div class="panel-body">

        <!-- 回答済みの質問一覧 -->
        <% passive_questions.each do |passive| %>

            <span class="row">
                <span class="col-xs-1"></span>
                <span class="col-xs-7">
                    <%= link_to passive.title, question_path(passive) %>
                </span>
                <span class="col-xs-3 text-right">
                    <% if passive.status == false %>
                        <div class="statusbutton"> &nbsp;&nbsp;回答済み&nbsp;&nbsp; </div>
                    <% end %>
                </span>
                <span class="col-xs-1"></span>
            </span>

        <% end %>

        <!-- ページネーション -->
        <div class="row">
            <div class="col-xs-1"></div>
            <div class="col-xs-10"><%= paginate passive_questions %></div>
            <div class="col-xs-1"></div>
        </div>
    </div>
</div>

app/views/questions/_rank.html.erb
<div class="panel panel-default">
    <div class="panel-heading text-center">みんなが興味を持っている質問</div>
    <div class="panel-body">

        <% if ranks.present? %>
            <% ranks.each.with_index(1) do |rank,i| %>
                <span class="row">
                    <span class="col-xs-2 text-center">第 <%= i %> 位</span>
                    <span class="col-xs-7">
                        <%= link_to rank.title, question_path(rank) %>
                    </span>
                    <span class="col-xs-3 text-center">
                        <% if rank.status == true %>
                            <div class="statusbutton"> 回答受付中 </div>
                        <% else %>
                            <div class="statusbutton"> &nbsp;&nbsp;回答済み&nbsp;&nbsp;</div>
                        <% end %>
                    </span>
                </span>
            <% end %>
        <% end %>

    </div>
</div>

app/views/questions/_sympathize.html.erb
<% if question.sympathized_by?(current_user) %>

    <%= link_to question_sympathizes_path(question), method: :delete, remote: true do %>
        <span class="reactionall">
            <i class= "glyphicon glyphicon-thumbs-up" aria-hidden="true" style="color: blue;"></i>
            <span><%= question.sympathizes.count %>人がこの質問に興味を持っています</span>
        </span>
    <% end %>

<% else %>

    <%= link_to question_sympathizes_path(question), method: :post, remote: true do %>
        <span class="reactionall">
            <i class= "glyphicon glyphicon-thumbs-up" aria-hidden="true"></i>
            <span><%= question.sympathizes.count %>人がこの質問に興味を持っています</span>
        </span>
    <% end %>

<% end %>

app/views/questions/edit.html.erb
<body id="back">
    <p class="notice text-center"><%= notice %></p>
    <div class="panel panel-default">
        <div class="panel-heading text-center">
            <div class="panel-title">質問の編集</div>
        </div>
        <div class="panel-body ">

            <!-- 質問編集フォーム -->
            <%= form_with(model: @question, url: question_path(@question), local: true, method: :PATCH ) do |f| %>

                <table class="table table-hover table-inverse">
                    <tbody>
                        <tr>
                            <th>カテゴリー</th>
                            <td><%= f.collection_select(:category_id, Category.all, :id, :name, include_blank: "選択して下さい")%></td>
                        </tr>
                        <tr>
                            <th>タイトル</th>
                            <td><%= f.text_field(:title) %></td>
                        </tr>
                        <tr>
                            <th>内容</th>
                            <td><%= f.text_area(:content) %></td>
                        </tr>
                        <tr>
                            <th>ステータス</th>
                            <td>
                                <%= f.select(:status, [["回答受付中", true],["回答済み", false]]) %>
                            </td>
                        </tr>
                    </tbody>
                </table>

                <%= f.submit("更新する", class: "btn btn-default") %>

            <% end %>

        </div>
    </div>

    <!-- リンク -->
    <div class="question_show_link">
        <%= link_to "詳細画面へ戻る", question_path(@question), class: 'col-xs-12 btn btn-default' %>
    </div>

</body>

app/views/questions/index.html.erb
<body id="back">
    <div class="panel panel-default">
        <div class="panel-body">

            <!-- ランキング -->
            <%= render 'questions/rank', ranks: @ranks %>

            <!-- 新規投稿画面へのリンク -->
            <div class="question_index_link">
                <div class="col-xs-12">
                    <%= link_to "新しい質問を投稿する！", new_question_path, class: 'col-xs-12 btn btn-default' %>
                </div>
            </div>

            <!-- カテゴリー検索  -->
            <div id="category">
                <%= render 'categories/category', categories: @categories, category: @category, questions: @questions %>
            </div>

            <!-- 一覧表示 -->
            <%= render 'questions/index', active_questions: @active_questions, passive_questions: @passive_questions, questions: @questions  %>

        </div>
    </div>
</body>

app/views/questions/index.js.erb
$("#category").html("<%= j(render partial: 'categories/category', locals: { categories: @categories, category: @category, questions: @questions }) %>");

app/views/questions/new.html.erb
<body id="back">
    <p class="notice text-center"><%= notice %></p>
    <div class="panel panel-default">
        <div class="panel-heading text-center">質問を投稿する</div>
        <div class="panel-body">

            <!-- 質問新規投稿フォーム -->
            <%= form_with(model: @question, url: questions_path, local: true) do |f| %>

                <div class="select">
                    <span class="col-xs-6">カテゴリー</span>
                    <span class="col-xs-6 text-left">
                        <%= f.collection_select(:category_id, Category.all, :id, :name, include_blank: "選択して下さい")%>
                    </span>
                </div>

                <div class="select">
                    <span class="col-xs-6">質問ステータス</span>
                    <span class="col-xs-6 text-left">
                        <%= f.select(:status, [["回答受付中", true],["回答済み", false]]) %>
                    </span>
                </div>

                <div class="title col-xs-12">
                    <div>タイトル</div>
                    <div class="text-left"><%= f.text_field(:title, placeholder:"４０文字以内") %></div>
                </div>

                <div class="content col-xs-12 text-center">
                    <div>内容</div>
                    <div><%= f.text_area(:content) %></div>
                </div>

                <div class="col-xs-12 text-center">
                    <%= f.submit("質問を投稿する", class: "btn btn-default") %>
                </div>

            <% end %>

        </div>
    </div>

    <!-- リンク -->
    <div class="question_show_link">
        <%= link_to "一覧画面へ戻る", questions_path, class: 'col-xs-12 btn btn-default' %>
    </div>

</body>

app/views/questions/show.html.erb
<body id="back">
    <p class="notice text-center"><%= notice %></p>

    <!-- 質問詳細 -->
    <div class="panel panel-default">
        <div class="panel-heading text-center">
            <div class="panel-title">詳細</div>
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-1"></div>
                <div class="col-xs-3">

                    カテゴリー
                    <br><br>
                    ステータス
                    <br><br>
                    質問者
                    <br><br>
                    タイトル
                    <br><br>
                    内容
                    <br><br>

                </div>
                <div class="col-xs-7">

                    <%= @question.category.name %>
                    <br><br>
                    <% if @question.status == true %>
                        回答受付中
                    <% else %>
                        回答済み
                    <% end %>
                    <br><br>
                    <%= link_to @question.user.name, user_path(@question.user) %>
                    <br><br>
                    <%= @question.title %>
                    <br><br>
                    <%= simple_format(@question.content) %>
                    <br><br>

                </div>
                <div class="col-xs-1"></div>
            </div>

            <div class="question-action text-right">

                <!-- リアクション機能 -->
                <span id="sympathize-<%= @question.id %>">
                    <%= render 'questions/sympathize', question: @question %>
                </span>

                <!-- 各リンク -->
                <% if @question.user == current_user %>
                    <%= link_to "編集", edit_question_path(@question.id) %>
                    <%=link_to "削除", question_path(@question.id), method: :DELETE, "data-confirm" => "Are you sure?" %>
                <% end %>

                <!-- 日付 -->
                <%= @question.created_at.strftime('%Y/%m/%d') %>

            </div>
        </div>
    </div>

    <!-- 回答一覧 -->
    <%= render 'questions/answer', question: @question, answer: @answer %>

    <!-- 回答投稿フォーム -->
    <%= render 'questions/answer_form', question: @question, answer: @answer %>

    <!-- リンク -->
    <div class="question_show_link">
        <%= link_to "一覧画面へ戻る", questions_path, class: 'col-xs-12 btn btn-default' %>
    </div>

</body>