config/routes.rb
Rails.application.routes.draw do

    root to: 'homes#top'
    get 'home/about' => 'homes#about'

    get 'bookmarks/create'
    get 'bookmarks/destroy'

    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :users

    resources :articles do
        resource  :favorites, only: [:create, :destroy]
        resources :post_comments, only: [:create, :edit, :update, :destroy]
        resource  :bookmarks, only: [:create, :destroy]

        # ブックマークの一覧表示に使用するルーティング
        get			:bookmarks, on: :collection

    end

    resources :questions do
        resources :answers, only: [:create, :edit, :update, :destroy]
        resource  :sympathizes, only: [:create, :destroy]
    end

end

app/models/answer.rb
class Answer < ApplicationRecord

	belongs_to :user
	belongs_to :question

	validates :content, presence: true

	attachment :answer_image


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	has_many :bookmarks, dependent: :destroy

	# current_userが、対象の投稿に "いいね" または "ブックマーク" をしているか判定するメソッド

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
    end

  	def bookmark_by?(user)
    	bookmarks.where(user_id: user.id).exists?
  	end

  	# ここまで

	validates :town, presence: true, length: { maximum: 40 }
	validates :family_makeup, presence: true, length: { maximum: 40 }
	validates :maker, presence: true, length: { maximum: 40 }
	validates :sales_form, presence: true, length: { maximum: 40 }
	validates :modality, presence: true, length: { maximum: 40 }
	validates :style, presence: true, length: { maximum: 40 }
	validates :purchase_price, presence: true, length: { maximum: 40 }
	validates :content, presence: true

	attachment :article_image


end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :user
  belongs_to :article

  # 1人のユーザーが同じ投稿を複数回bookmarkできないようにする
  validates :user_id, uniqueness: { scope: :article_id }


end

app/models/category.rb
class Category < ApplicationRecord

	has_many :questions

end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :article

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :user
	belongs_to :article

	validates :comment, presence: true

	attachment :post_comment_image


end

app/models/question.rb
class Question < ApplicationRecord

	has_many :answers, dependent: :destroy
	has_many :sympathizes, dependent: :destroy

	belongs_to :user
	belongs_to :category

	validates :title, presence: true, length: { maximum: 40 }

	attachment :question_image

	def sympathized_by?(user)
		sympathizes.where(user_id: user.id).exists?
	end

end

app/models/sympathize.rb
class Sympathize < ApplicationRecord

	belongs_to :user
	belongs_to :question

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :sympathizes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # ブックマーク機能のアソシエーション
  has_many :bookmarks, dependent: :destroy

  # ユーザーがブックマークした投稿を直接アソシエーションで取得できるように"bookmark_articles"を定義
  has_many :bookmark_articles, through: :bookmarks, source: :article

  validates :name, presence: true, length: { maximum: 10 }

  attachment :profile_image

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :authenticate_user!

    def index
        # ランキング
        @ranks = Article.find(Favorite.group(:article_id).order('count(article_id) desc').limit(3).pluck(:article_id))
        # 一覧表示
        @articles = Article.page(params[:page]).reverse_order.per(8)
        # キーワード検索
        word = params[:search_word]

        @records = Article.where(

            "town LIKE? or
            family_makeup LIKE? or
            maker LIKE? or
            sales_form LIKE? or
            modality LIKE? or
            style LIKE? or
            purchase_price LIKE? or
            content LIKE?",
            "%#{word}%",
            "%#{word}%",
            "%#{word}%",
            "%#{word}%",
            "%#{word}%",
            "%#{word}%",
            "%#{word}%",
            "%#{word}%").page(params[:page]).reverse_order.per(4)
    end

    def show
        @article = Article.find(params[:id])
        @post_comment = PostComment.new
    end

    def new
        @article = Article.new
        @user = current_user
    end

    def create
         @article = Article.new(article_params)
         @article.user_id = current_user.id

         if @article.save
            flash[:notice] = "ご投稿ありがとうございました！"
            redirect_to article_path(@article)
        else
            flash[:notice] = "入力されていない項目があるか、字数制限を超過しています。"
            render(:new)
        end
    end

    def edit
        @article = Article.find(params[:id])

        if  @article.user_id != current_user.id
            flash[:notice] = "権限がありません。"
            redirect_to article_path(@article)
        end
    end

    def update
        @article = Article.find(params[:id])

        if  @article.update(article_params)
            flash[:notice] = "購入レポートを編集しました。"
            redirect_to article_path(@article)
        else
            flash[:notice] = "入力されていない項目があります。"
            render(:edit)
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

end

private

    def article_params
        params.require(:article).permit(:town, :family_makeup, :maker, :sales_form, :modality, :style, :purchase_price, :article_image, :content)
    end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def top
    end

    def about
    end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sympathizes_helper.rb
module SympathizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_bookmark.html.erb
<% if article.bookmark_by?(current_user) %>

    <%= link_to article_bookmarks_path(article.id), method: :delete, remote: true do %>
        <span class="reactionall">
            &nbsp;<i class= "glyphicon glyphicon-bookmark" aria-hidden="true" ></i>&nbsp;ブックマークを解除&nbsp;
        </span>
    <% end %>

<% else %>

    <%= link_to article_bookmarks_path(article.id), method: :post, remote: true do %>
        <span class="reactionall">
            &nbsp;<i class= "glyphicon glyphicon-bookmark" aria-hidden="true" ></i>&nbsp;ブックマーク&nbsp;
        </span>
    <% end %>

<% end %>

app/views/articles/_comment.html.erb
<div class="panel panel-default">
    <div class="panel-heading text-center">
        <div class="panel-title">コメント</div>
    </div>
    <div class="panel-body">
        <% if article.post_comments.blank? %>
            <div class="blank text-center">まだコメントがありません。</div>
        <% end %>

        <!-- コメント一覧 -->

        <% article.post_comments.each do |post_comment| %>

            <div class="panel">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-3">
                            <!-- コメントしたユーザーの画像と名前 -->
                            <%= link_to user_path(post_comment.user) do %>
                                <%= attachment_image_tag post_comment.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size: '50x50', class: "img-responsive center-block" %><br>
                                <p class= "text-center"><%=  post_comment.user.name %></p>
                            <% end %>
                        </div>
                        <div class="col-xs-8">
                            <!-- コメント本文 -->
                            <div class="comment">
                                <%= simple_format(post_comment.comment) %>
                            </div>
                            <!-- コメントに投稿した画像 -->
                            <div class="comment_image">
                                <%= attachment_image_tag post_comment, :post_comment_image, :fill, 500, 400, format: 'jpeg', class: "img-responsive center-block" %>
                            </div>
                        </div>
                        <div class="col-xs-1"></div>
                    </div>

                    <!-- リンクボタン・日付 -->
                    <div class="col-xs-12 text-right">
                        <span>
                            <% if post_comment.user == current_user %>
                                <%= link_to "編集", edit_article_post_comment_path(article,post_comment.id) %>
                                <%= link_to "削除", article_post_comment_path(article,post_comment.id), method: :DELETE, remote: true, "data-confirm" => "Are you sure?" %>
                            <% end %>
                        </span>
                        <span>
                            <%= post_comment.created_at.strftime('%Y/%m/%d') %>
                        </span>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/articles/_comment_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading text-center">
        <div class="panel-title">コメントを投稿する</div>
    </div>
    <div class="panel-body">

        <!-- コメント新規投稿フォーム -->

        <%= form_with(model:[article, post_comment], url: article_post_comments_path(article.id), method: :POST, remote: true) do |f| %>

            <table class="table table-hover table-inverse">
                <tbody>
                    <tr>
                        <!-- コメント本文 -->
                        <td><%= f.text_area(:comment)%></td>
                    </tr>
                    <tr>
                        <td>
                            <!-- 画像 -->
                            <div class="image_field col-xs-5">
                                <%= f.attachment_field :post_comment_image %>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>

            <%= f.submit("コメントを投稿する", class: "btn btn-default") %>

        <% end %>

        <!-- ここまで -->

    </div>
</div>

app/views/articles/_favorite.html.erb
<% if article.favorited_by?(current_user) %>

    <%= link_to article_favorites_path(article), method: :delete, remote: true do %>
        <span class="reactionall">
            &nbsp;<i class= "glyphicon glyphicon-heart-empty" aria-hidden="true" style="color: red;"></i>
            <%= article.favorites.count %>いいね！
        </span>
    <% end %>

<% else %>

    <%= link_to article_favorites_path(article), method: :post, remote: true do %>
        <span class="reactionall">
            &nbsp;<i class= "glyphicon glyphicon-heart-empty" aria-hidden="true"></i>
            <%= article.favorites.count %>いいね！
        </span>
    <% end %>

<% end %>

app/views/articles/_rank.html.erb
<div class="panel panel-default">
    <div class="panel-heading text-center">みんながいいねをしている購入レポート</div>
    <div class="panel-body">

        <!-- 「いいね」の数をもとにカウントした購入レポートを上から3番目まで表示 -->

        <% ranks.each.with_index(1) do |rank,i| %>

            <div class="col-xs-4">
                <div class="article panel panel-default">
                    <div class="panel-heading text-center">第 <%= i %> 位</div>
                    <div class="panel-body text-center">
                        <div>
                            <%= attachment_image_tag rank, :article_image, :fill, 300, 200, format: 'jpeg', class: "img-responsive center-block" %>
                        </div>
                        <div class="action">
                            <%= link_to "詳しくはこちら", article_path(rank), class: "btn btn-default col-xs-12" %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/articles/edit.html.erb
<body id="back">

    <p class="notice text-center"><%= notice %></p>

    <div class="panel panel-default">
        <div class="panel-heading text-center">購入レポートの編集</div>
        <div class="panel-body">

            <!-- 購入レポート編集フォーム -->

            <%= form_with(model: @article, url: article_path(@article), local: true) do |f| %>

                <div class="article_field">
                    <div>お住まい</div>
                    <div><%= f.text_field(:town) %></div>
                </div>


                <div class="article_field">
                    <div>家族構成</div>
                    <div><%= f.text_field(:family_makeup) %></div>
                </div>


                <div class="article_field">
                    <div>契約したハウスメーカー・工務店</div>
                    <div><%= f.text_field(:maker) %></div>
                </div>


                <div class="article_field">
                    <div>販売形態</div>
                    <div><%= f.text_field(:sales_form) %></div>
                </div>


                <div class="article_field">
                    <div>種類</div>
                    <div><%= f.text_field(:modality) %></div>
                </div>


                <div class="article_field">
                    <div>スタイル</div>
                    <div><%= f.text_field(:style) %></div>
                </div>


                <div class="article_field">
                    <div>費用</div>
                    <div><%= f.text_field(:purchase_price) %></div>
                </div>


                <div class="article_field">
                    <div>打ち合わせや購入時のエピソード</div>
                    <div><%= f.text_area(:content) %></div>
                </div>


                <div class="article_field">
                    <div class="text-left">外観や内観の画像</div>
                    <div class="image_field col-xs-5"><%= f.attachment_field :article_image %></div>
                </div>


                <div class="article_submit_field">
                    <%= f.submit("更新する", class: "btn btn-default") %>
    			</div>

            <% end %>

            <!-- ここまで -->

        </div>
    </div>

    <!-- リンク -->
    <div class="article_show_link">
        <%= link_to "詳細画面へ戻る", article_path(@article), class: 'col-xs-12 btn btn-default' %>
    </div>

</body>

app/views/articles/index.html.erb
<body id="back">
    <div class="panel panel-default">
        <div class="panel-body">

            <!-- ランキング -->
            <%= render 'articles/rank', ranks: @ranks %>

            <!-- 新規投稿画面へのリンク -->
            <div class="row article_index_link">
                <div class="col-xs-12">
                    <%= link_to "購入レポートを投稿する！", new_article_path, class: 'col-xs-12 btn btn-default' %>
                </div>
            </div>

            <!-- キーワード検索画面 -->
            <%= render 'searches/search', records: @records %>

            <!-- レポート一覧 -->
            <div class="panel panel-default">
                <div class="panel-heading text-center">投稿された購入レポート一覧</div>
                <div class="panel-body">

                    <% @articles.each do |article| %>

                        <div class="col-xs-6">
                            <div class="article panel panel-default">
                                <div class="panel-heading text-center">
                                    <%= link_to article.user.name + "様邸", user_path(article.user) %>
                                </div>
                                <div class="panel-body text-center">

                                    <!-- 画像 -->
                                    <div>
                                        <%= attachment_image_tag article, :article_image, :fill, 300, 200, format: 'jpeg', class: "img-responsive center-block" %>
                                    </div>

                                    <!-- 詳細画面へのリンク -->
                                    <div class="action">
                                        <%= link_to "詳しくはこちら", article_path(article), class: "btn btn-default col-xs-12" %>
                                    </div>
                                </div>
                            </div>
                        </div>

                    <% end %>

                    <!-- ページネーション -->
                    <div class="row">
                        <div class="col-xs-1"></div>
                        <div class="col-xs-10"><%= paginate @articles %></div>
                        <div class="col-xs-1"></div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>

app/views/articles/new.html.erb
<body id="back">

    <p class="notice text-center"><%= notice %></p>

    <div class="panel panel-default">
        <div class="panel-heading text-center">購入レポートを投稿する</div>
        <div class="panel-body">

            <!-- 購入レポート新規投稿フォーム -->

            <%= form_with(model: @article, url: articles_path, local: true) do |f| %>

                <div class="article_field">
                    <div>お住まい</div>
                    <div><%= f.text_field(:town, placeholder:"都道府県  または  エリア")%></div>
                </div>


                <div class="article_field">
                    <div>家族構成</div>
                    <div><%= f.text_field(:family_makeup, placeholder:"父  母  子供２人") %></div>
                </div>


                <div class="article_field">
                    <div>契約したハウスメーカー・工務店</div>
                    <div><%= f.text_field(:maker, placeholder:"〇〇ハウス・〇〇工務店") %></div>
                </div>


                <div class="article_field">
                    <div>販売形態</div>
                    <div><%= f.text_field(:sales_form, placeholder:"建売・注文住宅") %></div>
                </div>


                <div class="article_field">
                    <div>種類</div>
                    <div><%= f.text_field(:modality, placeholder:"木造・鉄骨") %></div>
                </div>


                <div class="article_field">
                    <div>スタイル</div>
                    <div><%= f.text_field(:style, placeholder:"平家・２階建て・３階建て・４階建て") %></div>
                </div>


                <div class="article_field">
                    <div>費用</div>
                    <div><%= f.text_field(:purchase_price, placeholder:"約〇〇万円") %></div>
                </div>


                <div class="article_field">
                    <div>打ち合わせや購入時のエピソード</div>
                    <div><%= f.text_area(:content) %></div>
                </div>


                <div class="article_image_field">
                    <div class="text-left">外観や内観の画像</div>
                    <div class="image_field col-xs-5"><%= f.attachment_field :article_image %></div>
                </div>


                <div class="article_submit_field">
                    <%= f.submit("購入レポートを投稿する", class: "btn btn-default") %>
                </div>

            <% end %>

            <!-- ここまで -->

        </div>
    </div>

    <!-- リンク -->
    <div class="article_show_link">
        <%= link_to "一覧画面へ戻る", articles_path, class: 'col-xs-12 btn btn-default' %>
    </div>

</body>

app/views/articles/show.html.erb
<body id="back">

    <p class="notice text-center"><%= notice %></p>

    <div class="panel panel-default">
        <div class="panel-heading text-center"><%= @article.user.name %>様邸</div>

        <div class="row">
            <div class="col-xs-1"></div>

            <!-- 購入レポート詳細画面 -->
            <div class="col-xs-10">
                <div class="panel-body text-center">
                    <div class="panel panel-default">
                        <div class="panel-body text-center">

                            <!-- 購入レポートメイン画像 -->
                            <div class="article-image">
                                <%= attachment_image_tag @article, :article_image, :fill, 850, 650, format: 'jpeg', class: "img-responsive center-block" %>
                            </div>

                            <!-- インフォメーション -->
                            <div class="article-info panel panel-default">
                                <div class="panel-heading text-center">Infomation</div>
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-xs-1"></div>
                                        <div class="col-xs-5 text-left">

                                            お住まい
                                            <br>
                                            家族構成
                                            <br>
                                            ハウスメーカー・工務店
                                            <br>
                                            販売形態
                                            <br>
                                            種類
                                            <br>
                                            スタイル
                                            <br>
                                            費用

                                        </div>

                                        <div class="col-xs-6 text-left">

                                            <%= @article.town %>
                                            <br>
                                            <%= @article.family_makeup %>
                                            <br>
                                            <%= @article.maker %>
                                            <br>
                                            <%= @article.sales_form %>
                                            <br>
                                            <%= @article.modality %>
                                            <br>
                                            <%= @article.style %>
                                            <br>
                                            <%= @article.purchase_price %>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- インフォメーションここまで -->

                            <!-- エピソード -->
                            <div class="article-episode panel panel-default">
                                <div class="panel-heading text-center">Episode</div>
                                <div class="panel-body text-left">
                                    <%= simple_format(@article.content) %>
                                </div>
                            </div>
                            <!-- エピソードここまで -->

                            <div class="article-action text-right">

                                <!-- いいね機能 -->
                                <span id="favorite-<%= @article.id %>">
                                    <%= render 'articles/favorite', article: @article %>
                                </span>

                                <!-- ブックマーク機能 -->
                                <span id="bookmark-<%= @article.id %>">
                                    <% if @article.user != current_user %>
                                        <%= render 'articles/bookmark', article: @article %>
                                    <% end %>
                                </span>

                                <!-- 各リンク -->
                                <% if @article.user == current_user %>
                                    <%= link_to "編集", edit_article_path(@article) %>
                                    <%= link_to "削除", article_path(@article.id), method: :DELETE, "data-confirm" => "Are you sure?" %>
                                <% end %>

                                <!-- 日付 -->
                                <%= @article.created_at.strftime('%Y/%m/%d') %>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- 購入レポート詳細画面ここまで -->

            <div class="col-xs-1"></div>
        </div>
    </div>

    <!-- コメント一覧表示 -->
    <div id="comment-<%= @article.id %>">
        <%= render 'articles/comment', article: @article, post_comment: @post_comment %>
    </div>

    <!-- コメント投稿フォーム -->
    <div id="comment_form-<%= @article.id %>">
        <%= render 'articles/comment_form', article: @article, post_comment: @post_comment %>
    </div>

    <!-- リンク -->
    <div class="article_show_link">
        <%= link_to "一覧画面へ戻る", articles_path, class: 'col-xs-12 btn btn-default' %>
    </div>

</body>