config/routes.rb
Rails.application.routes.draw do

    root to: 'homes#top'
    get 'home/about' => 'homes#about'

    get 'bookmarks/create'
    get 'bookmarks/destroy'

    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :users

    resources :articles do
        resource  :favorites, only: [:create, :destroy]
        resources :post_comments, only: [:create, :edit, :update, :destroy]
        resource  :bookmarks, only: [:create, :destroy]

        # ブックマークの一覧表示に使用するルーティング
        get			:bookmarks, on: :collection

    end

    resources :questions do
        resources :answers, only: [:create, :edit, :update, :destroy]
        resource  :sympathizes, only: [:create, :destroy]
    end

end

app/models/answer.rb
class Answer < ApplicationRecord

	belongs_to :user
	belongs_to :question

	validates :content, presence: true

	attachment :answer_image


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	has_many :bookmarks, dependent: :destroy

	# current_userが、対象の投稿に "いいね" または "ブックマーク" をしているか判定するメソッド

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
    end

  	def bookmark_by?(user)
    	bookmarks.where(user_id: user.id).exists?
  	end

  	# ここまで

	validates :town, presence: true, length: { maximum: 40 }
	validates :family_makeup, presence: true, length: { maximum: 40 }
	validates :maker, presence: true, length: { maximum: 40 }
	validates :sales_form, presence: true, length: { maximum: 40 }
	validates :modality, presence: true, length: { maximum: 40 }
	validates :style, presence: true, length: { maximum: 40 }
	validates :purchase_price, presence: true, length: { maximum: 40 }
	validates :content, presence: true

	attachment :article_image


end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :user
  belongs_to :article

  # 1人のユーザーが同じ投稿を複数回bookmarkできないようにする
  validates :user_id, uniqueness: { scope: :article_id }


end

app/models/category.rb
class Category < ApplicationRecord

	has_many :questions

end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :article

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :user
	belongs_to :article

	validates :comment, presence: true

	attachment :post_comment_image


end

app/models/question.rb
class Question < ApplicationRecord

	has_many :answers, dependent: :destroy
	has_many :sympathizes, dependent: :destroy

	belongs_to :user
	belongs_to :category

	validates :title, presence: true, length: { maximum: 40 }

	attachment :question_image

	def sympathized_by?(user)
		sympathizes.where(user_id: user.id).exists?
	end

end

app/models/sympathize.rb
class Sympathize < ApplicationRecord

	belongs_to :user
	belongs_to :question

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :sympathizes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # ブックマーク機能のアソシエーション
  has_many :bookmarks, dependent: :destroy

  # ユーザーがブックマークした投稿を直接アソシエーションで取得できるように"bookmark_articles"を定義
  has_many :bookmark_articles, through: :bookmarks, source: :article

  validates :name, presence: true, length: { maximum: 10 }

  attachment :profile_image

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def top
    end

    def about
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!

    def index
        @users = User.all.page(params[:page]).reverse_order.per(10)
    end

    def show
        @user = User.find(params[:id])
        @bookmarks = current_user.bookmark_articles.page(params[:page]).reverse_order.per(4)
        @articles = Article.where(user_id:params[:id])
		@questions = Question.where(user_id:params[:id]).page(params[:page]).reverse_order.per(5)
	end

    def edit
        @user = User.find(params[:id])

        if  @user.id != current_user.id
            flash[:notice] = "権限がありません。"
            redirect_to user_path(@user)
        end
    end

    def update
        @user = User.find(params[:id])

        if  @user.update(user_params)
            flash[:notice] = "ユーザー情報を更新しました。"
            redirect_to user_path(@user)
        else
            flash[:notice] = "入力されていない項目があります。"
            render(:edit)
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to root_path
    end

end

private

    def user_params
        params.require(:user).permit(:profile_image, :name, :content)
    end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sympathizes_helper.rb
module SympathizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_article.html.erb
<div class="panel panel-default">
    <div class="panel-heading text-center">投稿したレポート</div>
    <div class="panel-body text-center">
        <% if articles.blank? %>
            <div class="blank text-center">まだレポートが投稿されていません。</div>
        <% end %>

        <!-- レポート一覧表示 -->
        <% articles.each do |article| %>

            <div class="user_article_image">
                <%= attachment_image_tag article, :article_image, :fill, 450, 300, format: 'jpeg', class: "img-responsive center-block" %>
            </div>
            <div class="center-block">
                <%= link_to "詳細ページへ", article_path(article), class: "article_link btn btn-default" %>
            </div>

        <% end %>

    </div>
</div>

app/views/users/_user_bookmark.html.erb
<div class="panel panel-default">
    <div class="panel-heading text-center">ブックマークしたレポート</div>
    <div class="panel-body">
        <% if bookmarks.blank? %>
            <div class="blank text-center">ブックマークされているレポートはありません。</div>
        <% end %>

        <!-- ブックマーク一覧表示 -->
        <% bookmarks.each do |bookmark| %>

            <div class="col-xs-6">
                <div class="article panel panel-default">
                    <div class="panel-heading text-center">
                        <%= link_to bookmark.user.name + "様邸", user_path(bookmark.user) %>
                    </div>
                    <div class="panel-body text-center">
                        <div>
                            <%= attachment_image_tag bookmark, :article_image, :fill, 300, 200, format: 'jpeg', class: "img-responsive center-block" %>
                        </div>
                        <div class="action">
                            <%= link_to "詳細ページへ", article_path(bookmark), class: "btn btn-default col-xs-12" %>
                        </div>
                    </div>
                </div>
            </div>

        <% end %>

        <!-- ページネーション -->
        <div class="row">
            <div class="col-xs-1"></div>
            <div class="col-xs-10"><%= paginate bookmarks, class: "paginate" %></div>
            <div class="col-xs-1"></div>
        </div>
    </div>
</div>

app/views/users/_user_info.html.erb
<div class="row">

    <div class="col-xs-1"></div>

    <!-- プロフィールイメージ画像 -->
    <div class="col-xs-3">
        <%= attachment_image_tag user, :profile_image, :fill, 150, 150, format: 'jpeg', fallback: "no_image.jpg", size: '150x150',  class: "img-responsive center-block" %>
    </div>
    <!-- 自己紹介文 -->
    <div class="col-xs-7">
        <div class="user_content">
            <% if user.content.blank? %>
                <div class="blank text-center">紹介文を書きましょう！</div>
            <% end %>
            <div class="text-left">
                <%= simple_format(user.content, size: "328x150") %>
            </div>
        </div>
        <div class="user_edit_link text-right">
            <% if @user == current_user %>
                <%= link_to "ユーザー情報を設定する", edit_user_path(user.id), class: "btn btn-default" %>
            <% end %>
        </div>
    </div>

    <div class="col-xs-1"></div>

</div>

app/views/users/_user_question.html.erb
<div class="panel panel-default">
    <div class="panel-heading text-center">投稿した質問</div>
    <div class="panel-body">
        <% if questions.blank? %>
            <div class="blank text-center">まだ質問が投稿されていません。</div>
        <% end %>

        <!-- 質問一覧 -->
        <% questions.each do |question| %>

            <span class="row">
                <span class="my_page_question text-left col-xs-8">
                    <%= link_to question.title, question_path(question) %>
                </span>
                <span class="col-xs-4 text-right">
                    <% if question.status == true %>
                        <div class="statusbutton"> 回答受付中</div>
                    <% else %>
                        <div class="statusbutton">&nbsp;&nbsp;回答済み&nbsp;&nbsp;</div>
                    <% end %>
                </span>
            </span>

        <% end %>
    </div>

    <!-- ページネーション -->
    <div class="row">
        <div class="col-xs-1"></div>
        <div class="col-xs-10"><%= paginate questions, class: "paginate" %></div>
        <div class="col-xs-1"></div>
    </div>
</div>

app/views/users/edit.html.erb
<body id="back">
    <p class="notice text-center"><%= notice %></p>
    <div class="panel panel-default  text-center">
        <div class="panel-heading">ユーザー情報を編集する</div>
        <div class="panel-body">

            <!-- ユーザー情報編集フォーム -->
            <%= form_with(model: @user, url: user_path(@user), local: true) do |f| %>

                <div class="article_field">
                    <div>ニックネーム</div>
                    <div><%= f.text_field(:name) %></div>
                </div>

                <div class="article_field">
                    <div>紹介文</div>
                    <div><%= f.text_area(:content) %></div>
                </div>

                <div class="article_field">
                    <div class="text-left">プロフィール画像</div>
                    <div class="image_field col-xs-5"><%= f.attachment_field :profile_image %></div>
                </div>

                <div class="article_submit_field">
                    <%= f.submit("設定を更新する", class: "btn btn-default") %>
                </div>

            <% end %>
        </div>
    </div>

    <!-- 退会ボタン -->
    <div class="panel panel-default text-center">
        <div class="panel-heading">ユーザー情報を削除する</div>
        <div class="panel-body">
            <div class="article_field">
                <%=link_to "退会する", user_path(@user.id), method: :DELETE, class:"btn btn-danger col-xs-12", "data-confirm" => "Are you sure?" %>
            </div>
        </div>
    </div>
</body>

app/views/users/index.html.erb
<body id="back">
    <div class="panel panel-default">
        <div class="panel-heading text-center">ユーザー一覧ページ</div>
        <div class="panel-body">
            <table class="table table-hover table-inverse">
                <thead>
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th>&nbsp;&nbsp;image</th>
                        <th>name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                    <% @users.each do |user| %>

                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>
                                <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", size: '60x60' %>
                            </td>
                            <td>
                                <%= user.name %>
                            </td>
                            <td>
                                <%= link_to "詳細ページへ", user_path(user) %>
                            </td>
                        </tr>

                    <% end %>

                </tbody>
            </table>

            <!-- ページネーション -->
            <span class="row">
                <span class="col-xs-1"></span>
                <span class="col-xs-10"><%= paginate @users, class: "paginate" %></span>
                <span class="col-xs-1"></span>
            </span>
        </div>
    </div>
</body>

app/views/users/show.html.erb
<body id="back">
    <p class="notice text-center"><%= notice %></p>

    <!-- 親パネル -->
    <div class="panel panel-default">
        <div class="panel-heading text-center">
            <%= @user.name %>さんのマイページ
        </div>
        <div class="panel-body">
            <!-- ユーザー情報 -->
            <%= render 'users/user_info', user: @user %>

            <!-- 各リンク -->
            <% if @user == current_user %>
                <div class="row user_show_link">
                    <div class="col-xs-1"></div>
                    <div class="user_link col-xs-5">
                        <%= link_to "みんなの質問を見にいく", questions_path, class: 'col-xs-12 btn btn-default' %>
                    </div>
                    <div class="user_link col-xs-5">
                        <%= link_to "みんなの購入レポートを見にいく", articles_path, class: 'col-xs-12 btn btn-default' %>
                    </div>
                    <div class="col-xs-1"></div>
                </div>
            <% end %>

            <!-- 各一覧 -->
            <div class="row">
                <div class="col-xs-1"></div>
                <div class="col-xs-10">
                    <!-- ブックマークをした投稿一覧（ブックマーク一覧は @user == current_user の場合のみ表示） -->
                    <% if @user == current_user %>
                        <%= render 'users/user_bookmark', bookmarks: @bookmarks %>
                    <% end %>

                    <!-- ユーザーが投稿したレポート -->
                    <%= render 'users/user_article', articles: @articles %>

                    <!-- ユーザーが投稿した質問 -->
                    <%= render 'users/user_question', questions: @questions %>
                </div>
                <div class="col-xs-1"></div>
            </div>
        </div>
    </div>
</body>