config/routes.rb
Rails.application.routes.draw do

    root to: 'homes#top'
    get 'home/about' => 'homes#about'

    get 'bookmarks/create'
    get 'bookmarks/destroy'

    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :users

    resources :articles do
        resource  :favorites, only: [:create, :destroy]
        resources :post_comments, only: [:create, :edit, :update, :destroy]
        resource  :bookmarks, only: [:create, :destroy]

        # ブックマークの一覧表示に使用するルーティング
        get			:bookmarks, on: :collection

    end

    resources :questions do
        resources :answers, only: [:create, :edit, :update, :destroy]
        resource  :sympathizes, only: [:create, :destroy]
    end

end

app/models/answer.rb
class Answer < ApplicationRecord

	belongs_to :user
	belongs_to :question

	validates :content, presence: true

	attachment :answer_image


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	has_many :bookmarks, dependent: :destroy

	# current_userが、対象の投稿に "いいね" または "ブックマーク" をしているか判定するメソッド

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
    end

  	def bookmark_by?(user)
    	bookmarks.where(user_id: user.id).exists?
  	end

  	# ここまで

	validates :town, presence: true, length: { maximum: 40 }
	validates :family_makeup, presence: true, length: { maximum: 40 }
	validates :maker, presence: true, length: { maximum: 40 }
	validates :sales_form, presence: true, length: { maximum: 40 }
	validates :modality, presence: true, length: { maximum: 40 }
	validates :style, presence: true, length: { maximum: 40 }
	validates :purchase_price, presence: true, length: { maximum: 40 }
	validates :content, presence: true

	attachment :article_image


end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :user
  belongs_to :article

  # 1人のユーザーが同じ投稿を複数回bookmarkできないようにする
  validates :user_id, uniqueness: { scope: :article_id }


end

app/models/category.rb
class Category < ApplicationRecord

	has_many :questions

end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :article

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :user
	belongs_to :article

	validates :comment, presence: true

	attachment :post_comment_image


end

app/models/question.rb
class Question < ApplicationRecord

	has_many :answers, dependent: :destroy
	has_many :sympathizes, dependent: :destroy

	belongs_to :user
	belongs_to :category

	validates :title, presence: true, length: { maximum: 40 }

	attachment :question_image

	def sympathized_by?(user)
		sympathizes.where(user_id: user.id).exists?
	end

end

app/models/sympathize.rb
class Sympathize < ApplicationRecord

	belongs_to :user
	belongs_to :question

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :sympathizes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # ブックマーク機能のアソシエーション
  has_many :bookmarks, dependent: :destroy

  # ユーザーがブックマークした投稿を直接アソシエーションで取得できるように"bookmark_articles"を定義
  has_many :bookmark_articles, through: :bookmarks, source: :article

  validates :name, presence: true, length: { maximum: 10 }

  attachment :profile_image

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <title>iemaru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/3ccf672dcb.js" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <!-- ヘッダー -->

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <div class="navbar-brand"><%= link_to "i e m a r u ", root_path %></div>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">

              <% if user_signed_in? %>

                <li><%= link_to " Users ", users_path %></li>

                <li><%= link_to " My page ", user_path(current_user.id) %></li>

                <li><%= link_to " Question ", questions_path %></li>

                <li><%= link_to " Report ", articles_path %></li>

                <li><%= link_to " Logout", destroy_user_session_path, method: :delete %></li>

              <% else %>

                <li><%= link_to " Home", root_path %></li>

                <li><%= link_to " About", home_about_path %></li>

                <li><%= link_to " Sign up", new_user_registration_path %></li>

                <li><%= link_to " Login", new_user_session_path %></li>

              <% end %>

            </ul>
        </div>
      </div>
    </nav>

    <div id="wrapper">
      <div class="container">
        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-8">

            <%= yield %>

          </div>
          <div class="col-md-2"></div>
        </div>
      </div>
    </div>

    <!-- フッター -->
    <footer class="footer">
      <nav class="footer_navi navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-footer"></div>
        </div>
      </nav>
    </footer>

  </body>
</html>